### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by matejstrasek** [brownieboy/react-bootstrap-native-slider#8]
As it is made from bootstrap-slider library, how do i get to reproduce [example 1](http://seiyria.com/bootstrap-slider/) from the bootstrap-slider with this one?

In general, examples like they are done [here](http://seiyria.com/bootstrap-slider/) would be more than great.

**Comment by brownieboy** [comment]
I'm not sure what you mean.

The Readme for the project gives an example of how to call the component.  You can also check the file /src/js/app.jsx to see how I call it my own demo, which is an equivalent to the Example 1 that you reference above.

Remember that this control is essentially a front-end to the native HTML5 slider.  I use [my own react-bootstrap-slider](https://github.com/brownieboy/react-bootstrap-slider) component (which is just a 
React front-end to [seiyria's Bootstrap Slider component](https://github.com/seiyria/bootstrap-slider) component) as a polyfill for the native one in certain circumstances only.  It makes no sense to add extra functionality here that can't be reproduced in the native component.

**Comment by matejstrasek** [comment]
I was referring more to get the same look and feel as in the other demo (tooltip and CSS), but I guess, as you said, it's not part of the library.
